services:
  - type: web
    name: goodfire-feature-explorer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn goodfire_webapp.app:app --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    staticPublishPath: ./goodfire_webapp/static 